from database import 

class AuthService:
    async def login(): ...

    async def register(): ...

    async def get_user_by_id(): ...

    async def edit_user(): ...

    async def remove_user(): ...
