[tool.poetry]
name = "authservice"
version = "0.1.0"
description = "auth service for shop"
authors = ["Ilya Kozlobrodov <kozlobrodov.ilya@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.11"
python-jose = "^3.4.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
bcrypt = "4.0.1"
pydantic-settings = "^2.8.1"
sqlalchemy = "^2.0.39"
aioredis = "^2.0.1"
asyncpg = "^0.30.0"
alembic = "^1.15.1"
uvicorn = "^0.34.0"
pydantic = {extras = ["email"], version = "^2.11.2"}
celery = {extras = ["redis"], version = "^5.5.0"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
